### ISSUE TITLE
Audible chapters metadata not being written when merging multiple mp3 files audiobooks.

### ISSUE THREAD

**Issue by garlik82** [djdembeck/m4b-merge#37]
Hi.
When merging multiple mp3 files audiobook into one m4b file, the audible chapter data isn't written on the merged file, it will use the chapters.txt created during the merge process, so after this, we have to reprocess the merged m4b file again for the Audible chapter metadata to be written. Don't know if this is intended.

Sorry for my English and congrats for your awesome work.

**Comment by djdembeck** [comment]
Hello,

Yes, this is intentional. Most of the time mp3s indicate the book was sourced either from another service or from CD, thus having different times then audible. 90% of the time m4b/m4a files come from audible

**Comment by garlik82** [comment]
Thanks for your response. That makes sense.
