### ISSUE TITLE
Error with recent release

### ISSUE THREAD

**Issue by garlik82** [djdembeck/m4b-merge#44]
Getting this error.

Audiobook ASIN: 1980035962
INFO:root:Validated ASIN: 1980035962
Traceback (most recent call last):
  File "/opt/homebrew/bin/m4b-merge", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/m4b_merge/__main__.py", line 135, in main
    validate_args(parser.parse_args())
  File "/opt/homebrew/lib/python3.9/site-packages/m4b_merge/__main__.py", line 85, in validate_args
    run_all(inputs)
  File "/opt/homebrew/lib/python3.9/site-packages/m4b_merge/__main__.py", line 33, in run_all
    m4b.run_merge()
  File "/opt/homebrew/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 239, in run_merge
    self.prepare_data()
  File "/opt/homebrew/lib/python3.9/site-packages/m4b_merge/m4b_helper.py", line 64, in prepare_data
    for narrators in self.metadata['narrators']:
KeyError: 'narrators'

Latest m4b-merge, bragibooks gives the same error.

EDIT: narrator info is missing from audnexus api. maybe audible problem?

**Comment by djdembeck** [comment]
Great find! There are 2 things I need to implement to prevent this problem:
1. Periodic data refresh on Audnexus. The current issue is this book was ingested before it was released and now is stale.
2. Better handling of missing data in m4b-merge.

**Comment by garlik82** [comment]
Glad I could help. I assume audnexus.bundle will have the same problem with this book?

**Comment by djdembeck** [comment]
Yes, though the bundle should handle the error correctly. I've written an update entry function into the API, though it needs to be tested some more before being written into the clients. It looks like this:
`https://api.audnex.us/books/1980035962?update=0`. Pending Cloudflare cache, will update the entry in the database for you. I've already run the above URL and this issue should be resolved whenever cloudflare cache expires in a day.

As for better error prevention, I'll get to that when I can in m4b-merge

**Comment by garlik82** [comment]
> I think it may be prudent to not allow ingesting pre-order date books; what do you think?

I agree. No need to have books that aren't out in the db, and it might avoid problems.

**Comment by djdembeck** [comment]
Working on an automated periodic refresh. The API now will not allow adding a book before it's release date. m4b-merge should handle missing narrators and authors (in branch `develop`).
