### ISSUE TITLE
Multiple Docker issues

### ISSUE THREAD

**Issue by dweomer21** [djdembeck/m4b-merge#55]
I'm having trouble getting m4b-merge to work using the Docker method, and I'm hoping to get some clarification on some things. It doesn't seem like the Docker method was ever tested, based on how severe the following errors are, but I'd really love to get it working in Docker so I don't have to mess around with directly installing python modules, and all dependencies needed, etc. Any pointers would be appreciated!

With regards to this:
> You'll need to specify input/output volumes in the run command for easy use later:
> `docker run --name=merge -v /input:/path/to/input -v /output:/path/to/output ghcr.io/djdembeck/m4b-merge:main`

  Unless I am missing some obscure usage of Docker, the volume parameters are reversed (`/input:/path/to/input` should be `/path/to/input:/input`, and same for the output volume). This is an easy one to fix, but then there is another fatal error:
`runuser: options --{shell,fast,command,session-command,login} and --user are mutually exclusive`
  Best guess, based on some googling, is that there needs to be a `--` separator after the `-u user` parameter so that any other parameters are not glommed in with the `-u user` parameter. 
  This seems to have worked, but after all of that, I am presented with an `m4b-merge` usage message informing me that the `-i` parameter is required:
`m4b-merge: error: the following arguments are required: -i/--inputs`
This makes me think this entire docker command could be replaced with a simple `alias` like in [m4b-tool's docs](https://github.com/sandreas/m4b-tool#docker).

Thanks ahead of time for any pointers or assistance!

**Comment by djdembeck** [comment]
Good catch on the docs having paths reversed!

I'm not sure where you started down the path with errors though. In the README it shows how to put an input to the docker:
```
docker run -it merge m4b-merge -i /input/file.mp3
```

Or you can run the image detached using `-d`, and then just `docker exec -it merge` and run `m4b-merge -i /input/file.mp3` from inside the container's shell.

**Comment by dweomer21** [comment]
Ok, I have it working now, and I kinda can't believe this had me so stumped. I'm by no means a docker god, but I work with both podman and docker often, so I can only chalk this up to a bunch of little issues and mixups on my part, in addition to the error I mentioned in my first comment (`runuser: options --{shell,fast,command,session-command,login} and --user are mutually exclusive`). I had fixed this error in my local repo, but then switched to develop branch and didn't notice I had overwritten the fix, so that sent me down another windy alleyway for a while.

I'll try to make some time soon to submit a pull request for the `runuser` error I mentioned (if you aren't hitting this error, we probably just have different dev environments with different docker versions.
Once that is fixed, the subsequent `docker run -it merge ...` calls will succeed, since there will be a running container with that name, and all will be good.
